import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createMaxConnector} from '../lib/server/connectors/max.ts';
import {resolveConnector} from '../lib/server/connectors/registry.ts';
import type {SocialConnector,PublishInput,PublishResult} from '../lib/server/connectors/types.ts';
const token='MAX_TEST_ONLY_secret';
const input:PublishInput={publicationId:'p',provider:'MAX',destinationId:'-12345',text:'Привет <мир> & 😜'};
const message={message:{recipient:{chat_id:-12345,chat_type:'chat'},timestamp:1,body:{mid:'mid.test_42',seq:1,text:input.text,attachments:null}}};
type Req={url:URL,headers:Headers,body:unknown,method:string};
type Connector=SocialConnector & {validate?: (id:string)=>Promise<{ok:true,destinationId:string,displayName:string}|Extract<PublishResult,{ok:false}>>};
async function wire(run:(c:Connector,requests:Req[])=>Promise<void>,reply:(r:Req)=>{status?:number,body:unknown,raw?:boolean}=()=>({body:message})) {
 const requests:Req[]=[];const originalFetch=globalThis.fetch;const previous=process.env.MAX_BOT_TOKEN;process.env.MAX_BOT_TOKEN=token;
 const server=createServer(async(req,res)=>{const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(typeof v==='string')headers.set(k,v);const raw=Buffer.concat(chunks);const body=raw.length ? headers.get('content-type')?.includes('multipart') ? await new Request('http://localhost',{method:'POST',headers,body:raw}).formData():JSON.parse(raw.toString()):null;const r={url:new URL(req.url!,'https://platform-api2.max.ru'),headers,body,method:req.method!};requests.push(r);const response=reply(r);res.writeHead(response.status??200,{'content-type':response.raw?'text/plain':'application/json'}).end(response.raw?String(response.body):JSON.stringify(response.body));});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address!=='string');
 globalThis.fetch=(url,init)=>{const u=new URL(String(url));assert.ok(['platform-api2.max.ru','iu.oneme.ru','omub.okcdn.ru'].includes(u.hostname));assert.equal(u.protocol,'https:');assert.equal(init?.redirect,'error');assert.ok(!u.search.includes(token));if(u.hostname!=='platform-api2.max.ru'&&u.hostname!=='iu.oneme.ru')assert.equal(new Headers(init?.headers).get('authorization'),null);return originalFetch(`http://127.0.0.1:${address.port}${u.pathname}${u.search}`,init);};
 try {await run(resolveConnector('MAX') as Connector,requests);}finally{globalThis.fetch=originalFetch;if(previous===undefined)delete process.env.MAX_BOT_TOKEN;else process.env.MAX_BOT_TOKEN=previous;server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
}
const validReply=(r:Req)=>({body:r.url.pathname==='/me'?{user_id:7,is_bot:true,username:'se14310498_bot',first_name:'Bot'}:r.url.pathname==='/chats/-12345'?{chat_id:-12345,type:'chat',status:'active',title:'Test group',is_public:true,last_event_time:1,participants_count:2,icon:null,description:null}:r.url.pathname.endsWith('/members/me')?{user_id:7,is_bot:true,is_admin:true,is_owner:false,permissions:['write'],first_name:'Bot',last_activity_time:1,join_time:1,last_access_time:1,username:'se14310498_bot'}:message});
test('MAX validates bot, active chat and matching administrator before connecting',async()=>{await wire(async(c,rs)=>{assert.equal(typeof c.validate,'function');assert.deepEqual(await c.validate!('-12345'),{ok:true,destinationId:'-12345',displayName:'Test group'});assert.deepEqual(rs.map(r=>r.url.pathname),['/me','/chats/-12345','/chats/-12345/members/me']);},validReply);});
test('MAX sends literal text once with header credentials and confirms matching remote ID',async()=>{await wire(async(c,rs)=>{assert.deepEqual(await c.publish(input),{ok:true,remoteId:'mid.test_42',remoteUrl:null});assert.equal(rs.length,1);assert.equal(rs[0].headers.get('authorization'),token);assert.equal(rs[0].url.searchParams.get('chat_id'),'-12345');assert.deepEqual(rs[0].body,{text:input.text,attachments:[]});});});
for(const[type,mime]of[['image','image/png'],['video','video/mp4']] as const){test(`MAX ${type} uploads actual private bytes and sends a confirmed attachment token`,async()=>{await wire(async(c,rs)=>{assert.equal((await c.publish({...input,media:[{name:'test',mimeType:mime,bytes:new Uint8Array([1,2,3])}]})).ok,true);assert.deepEqual(rs.map(r=>r.url.pathname),['/uploads',type==='image'?'/uploadImage':'/upload.do','/messages']);assert.equal(rs[0].url.searchParams.get('type'),type);const form=rs[1].body as FormData;assert.deepEqual([...new Uint8Array(await(form.get('data') as File).arrayBuffer())],[1,2,3]);assert.deepEqual(rs[2].body,{text:input.text,attachments:[{type,payload:{token:'attachment-token'}}]});},r=>r.url.pathname==='/uploads'?{body:{url:type==='image'?'https://iu.oneme.ru/uploadImage?signature=public-test':'https://omub.okcdn.ru/upload.do?signature=public-test',token:type==='video'?'attachment-token':undefined}}:r.url.pathname==='/uploadImage'?{body:{photos:{'photo-id':{token:'attachment-token'}}}}:r.url.pathname==='/upload.do'?{body:'<retval>1</retval>',raw:true}:{body:message});});}
test('MAX ordered mixed attachments upload separately and preserve order in one message',async()=>{let n=0;await wire(async(c,rs)=>{assert.equal((await c.publish({...input,media:[{name:'a',mimeType:'image/png',bytes:new Uint8Array([1])},{name:'b',mimeType:'video/mp4',bytes:new Uint8Array([2])}]})).ok,true);assert.deepEqual((rs.at(-1)!.body as {attachments:unknown[]}).attachments,[{type:'image',payload:{token:'image-token'}},{type:'video',payload:{token:'video-token'}}]);},r=>r.url.pathname==='/uploads'?{body:++n===1?{url:'https://iu.oneme.ru/uploadImage'}:{url:'https://omub.okcdn.ru/upload.do',token:'video-token'}}:r.url.pathname==='/uploadImage'?{body:{photos:{one:{token:'image-token'}}}}:r.url.pathname==='/upload.do'?{body:'<retval>1</retval>',raw:true}:{body:message});});
test('MAX invalid content is rejected before requests',async()=>{await wire(async(c,rs)=>{for(const bad of[{...input,text:'x'.repeat(4001)},{...input,destinationId:'9007199254740993'},{...input,destinationId:'https://evil.test'},{...input,media:[{name:'x',mimeType:'image/webp',bytes:new Uint8Array([1])}]}]){const result=await c.publish(bad);assert.equal(result.ok,false);if(!result.ok)assert.equal(result.errorType,'VALIDATION');}assert.equal(rs.length,0);});});
for(const[status,errorType]of[[401,'AUTH'],[403,'AUTH'],[429,'TEMPORARY']] as const){test(`MAX HTTP${status} is safely normalized`,async()=>{await wire(async c=>{const r=await c.publish(input);assert.equal(r.ok,false);if(!r.ok)assert.equal(r.errorType,errorType);assert.ok(!JSON.stringify(r).includes(token));},()=>({status,body:{code:'error',message:token}}));});}
test('MAX explicit attachment.not.ready is retryable, lost confirmation is ambiguous',async()=>{await wire(async c=>{const r=await c.publish(input);assert.equal(r.ok,false);if(!r.ok){assert.equal(r.errorType,'TEMPORARY');assert.equal(r.retryAfterMs,60000);}},()=>({status:400,body:{code:'attachment.not.ready',message:token}}));await wire(async c=>{const r=await c.publish(input);assert.equal(r.ok,false);if(!r.ok){assert.equal(r.code,'AMBIGUOUS_DELIVERY');assert.equal(r.errorType,'PERMANENT');}},()=>({body:{message:{...message.message,recipient:{chat_id:-999,chat_type:'chat'}}}}));});
test('MAX unsafe upload URLs never receive private bytes or credentials',async()=>{for(const url of['http://iu.oneme.ru/uploadImage','https://127.0.0.1/uploadImage','https://iu.oneme.ru.evil.test/uploadImage','https://iu.oneme.ru:444/uploadImage','https://user:pass@iu.oneme.ru/uploadImage'])await wire(async(c,rs)=>{const r=await c.publish({...input,media:[{name:'x',mimeType:'image/png',bytes:new Uint8Array([1])}]});assert.equal(r.ok,false);assert.equal(rs.length,1);},()=>({body:{url}}));});

test('MAX rejects private, inactive, unsafe ID and non-admin destination without fake connection',async()=>{
 for(const change of[{type:'dialog'},{status:'left'},{chat_id:9007199254740992},{is_admin:false}])await wire(async c=>{
  assert.equal(typeof c.validate,'function');const result=await c.validate!('-12345');assert.equal(result.ok,false);
 },r=>{const response=validReply(r);if(r.url.pathname==='/chats/-12345')return {body:{...(response.body as object),...('is_admin' in change?{}:change)}};if(r.url.pathname.endsWith('/members/me')&&'is_admin' in change)return {body:{...(response.body as object),...change}};return response;});
});

test('MAX transport exceptions before upload and after message handoff have different retry outcomes',async()=>{
 for(const media of[[],[{name:'p',mimeType:'image/png',bytes:new Uint8Array([1])}]])await wire(async c=>{
  const isolated=createMaxConnector({token,fetcher:async()=>{throw new Error(`transport ${token}`);}});const result=await isolated.publish({...input,media});assert.equal(result.ok,false);
  if(!result.ok)assert.equal(result.errorType,media.length?'TEMPORARY':'PERMANENT');assert.ok(!JSON.stringify(result).includes(token));
 });
});

test('MAX confirmed ID does not invent a group URL or accept an unsafe provider link',async()=>{
 for(const url of['https://evil.test/post','http://max.ru/post','https://user:pass@max.ru/post'])await wire(async c=>{assert.deepEqual(await c.publish(input),{ok:true,remoteId:'mid.test_42',remoteUrl:null});},()=>({body:{message:{...message.message,url}}}));
});

test('MAX permits image without caption',async()=>{await wire(async(c,rs)=>{assert.equal((await c.publish({...input,text:'',media:[{name:'photo',mimeType:'image/png',bytes:new Uint8Array([1])}]})).ok,true);assert.equal((rs.at(-1)!.body as {text:string}).text,'');},r=>r.url.pathname==='/uploads'?{body:{url:'https://iu.oneme.ru/uploadImage'}}:r.url.pathname==='/uploadImage'?{body:{photos:{one:{token:'image-token'}}}}:{body:message});});
