'use client';
import {useState} from 'react';
import {ArrowRight,CalendarDays,Check,Clock,Image as ImageIcon,Send,X,MoreHorizontal,Heart,MessageCircle,Bookmark,Upload} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {dateInput,networks,validatePost,type Media,type Network,type Post,type State,type Status} from '@/lib/planner';
import {Social,MediaView} from './planner';
export default function Composer({post,initialDate,data,upload,onSave}:{post:Post|null;initialDate:string;data:State;upload:()=>void;onSave:(p:Post)=>Promise<void>}){
 const [text,setText]=useState(post?.text||'');const [title,setTitle]=useState(post?.title||'');const [chosen,setChosen]=useState<Network[]>(post?.networks||data.accounts.slice(0,1));const [date,setDate]=useState(post?.date?dateInput(new Date(post.date)):initialDate||dateInput(new Date(Date.now()+86400000)));const [preview,setPreview]=useState<Network>(post?.networks[0]||'Telegram');const [media,setMedia]=useState<Media|undefined>(post?.media);const [showMedia,setShowMedia]=useState(false);const [error,setError]=useState('');
 const [busy,setBusy]=useState(false);const [publicUrl,setPublicUrl]=useState(post?.publicUrl||'');
 async function save(status:Status){if(busy)return;if(!Number.isFinite(new Date(date).getTime())){setError('Выберите дату.');return}const p:Post={id:post?.id||crypto.randomUUID(),title:title.trim()||text.trim().slice(0,64),text,networks:chosen,date:status==='published'?new Date().toISOString():new Date(date).toISOString(),status,media,publicUrl,revision:post?.revision};const err=validatePost(p);if(err){setError(err);return}if(status!=='draft'&&chosen.some(n=>!data.accounts.includes(n))){setError('Подключите выбранные соцсети на экране «Соцсети».');return}setError('');setBusy(true);try{await onSave(p)}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить пост.')}finally{setBusy(false)}}
 return <div className="composer-layout"><div className="composer-main"><section className="panel editor-panel"><div className="step-title"><span>1</span><h2>О чём расскажем?</h2><span className="muted">Контент</span></div><label>Название <span className="optional">· только для вас</span><input placeholder="Например, утро у моря" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/></label><label>Текст поста<textarea placeholder="Начните с одной мысли…" value={text} onChange={e=>setText(e.target.value)} rows={8} maxLength={10000}/></label><div className="editor-bottom"><button className="text-button" onClick={()=>setShowMedia(!showMedia)}><ImageIcon size={17}/>Добавить медиа</button><span>{text.length} символов</span></div>{showMedia&&<div className="media-picker"><button className="secondary" onClick={upload}><Upload size={16}/>Загрузить файл</button>{data.media.length===0&&<p className="muted">Загрузите первое фото или видео.</p>}<div>{data.media.map(m=><button aria-label={`Выбрать ${m.name}`} key={m.id} onClick={()=>{setMedia(m);setShowMedia(false)}}><MediaView media={m}/></button>)}</div></div>}{media&&<div className="attachment"><ImageIcon size={17}/><span>{media.name}</span><button aria-label="Убрать вложение" className="icon-button" onClick={()=>setMedia(undefined)}><X size={15}/></button></div>}</section>
 <section className="panel editor-panel"><div className="step-title"><span>2</span><h2>Куда публикуем?</h2></div><div className="network-select">{networks.map(n=><button key={n} className={chosen.includes(n)?'chosen':''} disabled={!data.accounts.includes(n)} onClick={()=>{setChosen(chosen.includes(n)?chosen.filter(x=>x!==n):[...chosen,n]);setPreview(n)}}><Social network={n} small/><span>{n}<small>{data.accounts.includes(n)?'Подключено':'Не подключено'}</small></span><span className="checkbox">{chosen.includes(n)&&<Check size={13}/>}</span></button>)}</div></section>
 {chosen.includes('Instagram')&&<section className="panel editor-panel"><label>Публичная HTTPS-ссылка на JPEG<input type="url" value={publicUrl} onChange={e=>setPublicUrl(e.target.value)} placeholder="https://ваш-сайт.ru/photo.jpg"/></label><p className="fine">Instagram должен иметь доступ к файлу без входа. Загрузка из приватной медиатеки для Instagram пока недоступна.</p></section>}<section className="panel editor-panel"><div className="step-title"><span>3</span><h2>Когда выйдет пост?</h2></div><label>Дата и время<input aria-label="Дата и время публикации" type="datetime-local" value={date} min={dateInput(new Date())} onChange={e=>setDate(e.target.value)}/></label><p className="fine"><Clock size={14}/> Часовой пояс устройства: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p></section>
 {error&&<p role="alert" className="error-message">{error}</p>}<div className="save-bar" inert={busy?true:undefined}><button className="secondary" onClick={()=>save('draft')}>В черновики</button><button className="text-button" onClick={()=>save('published')}>Опубликовать сейчас</button><Button className="primary" onClick={()=>save('scheduled')}><CalendarDays size={17}/>Запланировать</Button></div><p className="fine">Отправка начнётся после сохранения. Результат появится в журнале публикаций.</p></div>
 <aside className="preview-column"><div className="section-heading"><h2>Предпросмотр</h2><span className="pill">Пример</span></div><div className="preview-tabs">{networks.map(n=><button key={n} className={preview===n?'active':''} onClick={()=>setPreview(n)} aria-label={`Предпросмотр ${n}`}><Social network={n} small/></button>)}</div><div className={`social-preview preview-${preview.toLowerCase()}`}><div className="preview-header"><span className="avatar">{data.name[0]}</span><div><strong>{preview==='Instagram'?'danil_content':data.name+' | Личный блог'}</strong><small>{preview==='Telegram'?'Ваш канал':preview==='VK'?'сегодня в '+(date.slice(11)||'12:00'):'Сочи'}</small></div><MoreHorizontal size={18}/></div>{preview==='Instagram'&&(media?<div className="preview-media"><MediaView media={media}/></div>:<div className="instagram-placeholder"><ImageIcon size={32}/><p>Ваше фото или видео</p></div>)}{preview==='Instagram'&&<div className="preview-reactions"><Heart size={21}/><MessageCircle size={21}/><Send size={21}/><Bookmark size={21}/></div>}<div className="preview-text">{text||'Здесь появится ваш текст. Начните писать — и пост оживёт.'}</div>{preview!=='Instagram'&&media&&<div className="preview-media"><MediaView media={media}/></div>}<div className="preview-footer">{preview==='Telegram'?'Предпросмотр публикации':'♡ Нравится     ◯ Комментировать'}<span>{date.slice(11,16)}</span></div></div><p className="preview-disclaimer">Приблизительный вид публикации.<br/>Оформление в соцсети может отличаться.</p></aside></div>;
}
