 'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,CalendarDays,Check,ChevronLeft,ChevronRight,Clock,FileText,Image as ImageIcon,LayoutDashboard,Link2,LogOut,Plus,Search,Send,Settings,Trash2,X,Menu,Layers,Upload,CheckCircle2,PenLine,Copy,Zap,BarChart3,Bell,Lightbulb,LoaderCircle,AlertCircle} from 'lucide-react';
import Composer from './composer';
import {dateInput,networks,statusLabels,type Media,type Network,type Post,type State,type Status,type Delivery} from '@/lib/planner';
type View='dashboard'|'create'|'calendar'|'content'|'media'|'accounts'|'settings'|'analytics';
const nav=[{id:'dashboard',label:'Обзор',icon:LayoutDashboard},{id:'calendar',label:'Календарь',icon:CalendarDays},{id:'content',label:'Контент',icon:FileText},{id:'media',label:'Медиатека',icon:ImageIcon},{id:'analytics',label:'Публикации',icon:BarChart3},{id:'accounts',label:'Соцсети',icon:Link2}] as const;
const titles:Record<View,string>={dashboard:'Обзор',create:'Новый пост',calendar:'Календарь',content:'Контент',media:'Медиатека',accounts:'Социальные сети',settings:'Настройки',analytics:'Журнал публикаций'};
export function Social({network,small=false}:{network:Network;small?:boolean}){return <span title={network} className={`social ${network.toLowerCase()} ${small?'small':''}`}>{network==='Telegram'?<Send size={small?14:22}/>:network==='VK'?'vk':'◎'}</span>}
export function MediaView({media}:{media:Media}){return media.type.startsWith('video')?<video src={media.src} controls preload="metadata"/>:<img src={media.src} alt={media.name} loading="lazy"/>}
function Badge({status}:{status:Status}){return <span className={`badge ${status}`}><span/>{statusLabels[status]}</span>}
function fmt(value:string){return new Date(value).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}
function localDay(value:string){return dateInput(new Date(value)).slice(0,10)}
async function request(path:string,method='GET',value?:unknown){const response=await fetch(path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json','X-Planly-Request':'1'},...(value===undefined?{}:{body:JSON.stringify(value)})});const result=await response.json() as State & {error?:string};if(!response.ok)throw Object.assign(new Error(result.error||'Сервер недоступен'),{status:response.status});return result;}
export default function Planner(){
 const [data,setData]=useState<State|null>(null),[view,setView]=useState<View>('dashboard'),[toast,setToast]=useState(''),[error,setError]=useState(''),[auth,setAuth]=useState(false),[busy,setBusy]=useState(false),[mobile,setMobile]=useState(false),[narrow,setNarrow]=useState(false);
 const [editing,setEditing]=useState<Post|null>(null),[initialDate,setInitialDate]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[networkFilter,setNetworkFilter]=useState('all'),[month,setMonth]=useState(new Date()),[selected,setSelected]=useState<Post|null>(null),[day,setDay]=useState(localDay(new Date().toISOString())),[idea,setIdea]=useState(''),[connect,setConnect]=useState<Network|null>(null);
 const uploadRef=useRef<HTMLInputElement>(null),searchRef=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{try{const d=await request('/api/state');setData(d);setAuth(false);setError('')}catch(e){if((e as {status?:number}).status===401)setAuth(true);else setError(e instanceof Error?e.message:'Нет связи с сервером')}},[]);
 useEffect(()=>{const media=window.matchMedia('(max-width:740px)');const sync=()=>setNarrow(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[]);
 useEffect(()=>{void refresh();const sync=()=>{const v=location.hash.slice(1) as View;if(v in titles)setView(v)};sync();window.addEventListener('hashchange',sync);const timer=setInterval(()=>{if(document.visibilityState==='visible'){void refresh();void request('/api/tick','POST').catch(()=>{})}},15000);return()=>{clearInterval(timer);window.removeEventListener('hashchange',sync)}},[refresh]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);setConnect(null);setMobile(false)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 function go(v:View){location.hash=v;setView(v);setMobile(false)}
 function create(date=''){setEditing(null);setInitialDate(date);go('create')}
 async function action(work:()=>Promise<unknown>,message:string){if(busy)return;setBusy(true);try{await work();await refresh();setToast(message)}catch(e){setToast(e instanceof Error?e.message:'Не удалось выполнить действие')}finally{setBusy(false)}}
 async function save(p:Post){await request('/api/posts','POST',p);await refresh();go('content');setFilter('all');setQuery('');setToast(p.status==='draft'?'Черновик сохранён':'Пост добавлен в очередь');}
 async function upload(files:FileList|null){if(!files)return;await action(async()=>{for(const f of Array.from(files)){if(f.size>20*1024*1024)throw new Error('Максимум 20 МБ на файл.');const response=await fetch('/api/media',{method:'POST',headers:{'Content-Type':f.type,'X-Planly-Request':'1','X-File-Name':encodeURIComponent(f.name)},body:f});if(!response.ok)throw new Error((await response.json() as {error:string}).error)}},'Файлы загружены');}
 if(auth)return <main className="login"><div className="login-brand"><div className="brand"><span className="brand-mark"><Layers/></span>planly.</div><div><h1>Ваш контент.<br/>В вашем ритме.</h1><p>Создавайте, планируйте и публикуйте<br/>из одного личного пространства.</p><div className="login-networks">{networks.map(n=><Social key={n} network={n}/>)}</div></div><span>Personal SMM Planner</span></div><div className="login-form"><span className="pill">Личное пространство</span><h2>С возвращением</h2><p>Войдите, чтобы открыть ваши посты и подключённые каналы.</p><a className="primary wide signin" href="/signin-with-chatgpt?return_to=%2F" target="_top">Войти через ChatGPT <ArrowRight size={18}/></a><p className="fine">Доступ к этому планировщику открыт только владельцу.</p></div></main>;
 if(!data)return <div className="loading"><Layers size={30}/><p>{error||'Открываем ваше пространство…'}</p>{error&&<button className="secondary" onClick={()=>void refresh()}>Повторить</button>}</div>;
 const posts=data.posts,deliveries=data.deliveries||[],scheduled=posts.filter(p=>p.status==='scheduled').sort((a,b)=>a.date.localeCompare(b.date)),drafts=posts.filter(p=>p.status==='draft'),published=posts.filter(p=>p.status==='published'),problems=deliveries.filter(d=>['failed','unknown'].includes(d.status));
 const filtered=posts.filter(p=>(filter==='all'||p.status===filter)&&(networkFilter==='all'||p.networks.includes(networkFilter as Network))&&`${p.title} ${p.text}`.toLowerCase().includes(query.toLowerCase()));
 const start=new Date(month.getFullYear(),month.getMonth(),1),offset=(start.getDay()+6)%7,days=Array.from({length:42},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i-offset+1));
 const postRow=(p:Post)=><button key={p.id} className="post-row" onClick={()=>setSelected(p)}><time>{new Date(p.date).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</time><span className="row-networks">{p.networks.slice(0,2).map(n=><Social key={n} network={n} small/>)}</span><span className="post-thumb">{p.media?.type.startsWith('image')?<img src={p.media.src} alt=""/>:<FileText size={22}/>}</span><span className="post-info"><strong>{p.title}</strong><span>{fmt(p.date)} · {p.media?'Медиа':'Текст'}</span></span><Badge status={p.status}/><ChevronRight size={16}/></button>;
 return <><input ref={uploadRef} type="file" hidden multiple accept="image/png,image/jpeg,image/webp,video/mp4" onChange={e=>{void upload(e.target.files);e.target.value=''}}/><div className="app-shell" inert={selected||connect?true:undefined}>
 <aside className={`sidebar ${mobile?'open':''}`} inert={narrow&&!mobile?true:undefined}><a className="brand" href="#dashboard"><span className="brand-mark"><Layers size={23}/></span>planly.</a><nav>{nav.map(n=><button key={n.id} onClick={()=>go(n.id)} className={view===n.id?'active':''}><n.icon size={20}/>{n.label}{n.id==='analytics'&&problems.length>0&&<span className="nav-count">{problems.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-note"><Zap size={23}/><strong>От идеи<br/>до публикации</strong><p>Создайте пост. Выберите сети.<br/>Назначьте время.</p><button className="primary wide" onClick={()=>create()}>Создать пост <Plus size={16}/></button></div><button onClick={()=>go('settings')} className={view==='settings'?'active':''}><Settings size={19}/>Настройки</button><a className="signout" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={18}/>Выйти из аккаунта</a></div></aside>
 {mobile&&<button aria-label="Закрыть меню" className="sidebar-scrim" onClick={()=>setMobile(false)}/>}
 <div className="main-shell"><header className="topbar"><button aria-label="Открыть меню" className="mobile-menu icon-button" onClick={()=>setMobile(true)}><Menu size={20}/></button><form className="global-search" onSubmit={e=>{e.preventDefault();setFilter('all');go('content')}}><Search size={18}/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по контенту, идеям, хештегам…" aria-label="Поиск по контенту"/><kbd>Ctrl K</kbd></form><div className="topbar-right"><button className="icon-button notifications" aria-label={`Ошибок публикации: ${problems.length}`} onClick={()=>go('analytics')}><Bell size={21}/>{problems.length>0&&<i/>}</button><button className="profile-button" onClick={()=>go('settings')}><span className="avatar">{data.name[0]}</span><span><strong>{data.name}</strong><small>Личный аккаунт</small></span></button></div></header>
 <main className={`main-content view-${view}`}>{error&&<div role="alert" className="info-banner">{error} <button onClick={()=>void refresh()}>Повторить</button></div>}{view==='dashboard'&&<div className="info-banner planner-focus"><strong>Новый фокус Planly:</strong> охваты, просмотры, лайки и переходы по объектам недвижимости. Идеи и шаблоны собраны для новостроек и апартаментов Черноморского побережья.</div>}
 {view==='dashboard'&&<><div className="page-heading"><div><h1>Привет, {data.name}! <span className="wave">👋</span></h1><p>«Хороший контент сегодня — большие возможности завтра»</p></div><div className="heading-right"><span>{new Date().toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}<small>Время создавать ✨</small></span><button className="primary" onClick={()=>create()}><Plus size={19}/>Создать пост</button></div></div>
 <div className="dashboard-grid"><div className="dashboard-main"><section className="stats">{[{label:'Запланировано',count:scheduled.length,note:'В вашем расписании',icon:CalendarDays,color:'blue',status:'scheduled'},{label:'Черновики',count:drafts.length,note:'Идеи ждут своего часа',icon:PenLine,color:'blue',status:'draft'},{label:'Опубликовано',count:published.length,note:'Подтверждено соцсетями',icon:Send,color:'green',status:'published'},{label:'Подключено соцсетей',count:data.accounts.length,note:'Ваши каналы в одном месте',icon:Link2,color:'violet',status:'accounts'}].map(s=><button key={s.label} className="stat-card" onClick={()=>{setFilter(s.status);go(s.status==='accounts'?'accounts':'content')}}><span className={`stat-icon ${s.color}`}><s.icon size={24}/></span><div><span className="stat-label">{s.label}</span><strong>{String(s.count).padStart(2,'0')}</strong><small>{s.note}</small></div></button>)}</section>
 <div className="dashboard-middle"><section className="panel weekly"><div className="section-heading"><div><h2><CalendarDays size={21}/>Ближайшие 7 дней</h2><p>Ваш контент-план. Выберите день, чтобы увидеть посты.</p></div><button className="secondary" onClick={()=>go('calendar')}>Открыть календарь <ArrowRight size={15}/></button></div><div className="week-strip">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);const value=localDay(d.toISOString()),count=scheduled.filter(p=>localDay(p.date)===value).length;return <button key={value} className={`week-day ${day===value?'today':''}`} onClick={()=>setDay(value)}><span>{d.toLocaleDateString('ru-RU',{weekday:'short'})}</span><strong>{d.getDate()}</strong><small>{count?`${count} пост.`:'—'}</small></button>})}</div><div className="day-posts">{posts.filter(p=>p.status!=='draft'&&localDay(p.date)===day).length?posts.filter(p=>p.status!=='draft'&&localDay(p.date)===day).map(postRow):<div className="day-empty"><CalendarDays size={26}/><h3>Здесь место для вашей истории</h3><p>На этот день публикаций пока нет.</p><button className="text-button" onClick={()=>create(day+'T18:00')}>Добавить пост <Plus size={16}/></button></div>}</div></section>
 <div className="dashboard-center"><section className="panel quick-idea"><h2><Zap size={24}/>Быстрая идея</h2><p>Сохраните мысль, пока она не убежала ✨</p><textarea aria-label="Быстрая идея" placeholder="Например: рассказать про рабочий процесс…" value={idea} onChange={e=>setIdea(e.target.value)} maxLength={10000}/><div className="idea-actions"><span>В черновики</span><button className="primary" disabled={!idea.trim()||busy} onClick={()=>void action(async()=>{await request('/api/posts','POST',{id:crypto.randomUUID(),title:idea.slice(0,64),text:idea,networks:[],date:new Date().toISOString(),status:'draft'});setIdea('')},'Идея сохранена в черновики')}>Сохранить идею <Send size={15}/></button></div></section><section className="panel delivery-summary"><div className="section-heading"><h2><BarChart3 size={22}/>Публикации</h2><button className="text-button" onClick={()=>go('analytics')}>Журнал <ArrowRight size={15}/></button></div><div className="delivery-metrics">{[['Отправлено',deliveries.filter(d=>d.status==='sent').length,'green'],['В очереди',deliveries.filter(d=>d.status==='pending').length,'blue'],['Ошибки',problems.length,'violet']].map(([label,count,color])=><div key={label} className={`metric ${color}`}><small>{label}</small><strong>{count}</strong><div className="metric-line"/></div>)}</div><p className="fine">Результаты отправки по каждой соцсети.</p></section></div></div>
 <section className="inspiration"><div><h2>Делайте сегодня то,<br/>что другие не хотят —<br/>завтра будете там, где другие не могут.</h2><p>Маленький шаг — новый пост.</p></div><button className="secondary" onClick={()=>create()}>Продолжать создавать <ArrowRight size={19}/></button></section></div>
 <aside className="dashboard-right"><section className="panel accounts-mini"><div className="section-heading"><h2><Zap size={21}/>Мои соцсети</h2><button aria-label="Настроить соцсети" className="icon-button" onClick={()=>go('accounts')}><Settings size={18}/></button></div>{networks.map(n=><button className="account-mini" key={n} onClick={()=>go('accounts')}><Social network={n}/><span><strong>{n}</strong><small>{data.accountDetails?.find(a=>a.network===n)?.label||'Не подключено'}</small></span><span className={`connection ${data.accounts.includes(n)?'connected':''}`}>{data.accounts.includes(n)?<Check size={13}/>:<Plus size={13}/>}</span></button>)}<button className="secondary wide" onClick={()=>go('accounts')}><Plus size={16}/>Подключить ещё</button></section><section className="panel useful"><h2><Lightbulb size={22}/>Полезное</h2>{[{label:'Идеи для контента',note:'Вернуться к вашим черновикам',icon:Lightbulb,run:()=>{setFilter('draft');go('content')}},{label:'Шаблон: полезный совет',note:'Проблема → решение → вопрос',icon:FileText,run:()=>{setEditing({id:crypto.randomUUID(),title:'Полезный совет',text:'С какой проблемой сталкивается моя аудитория?\n\nЧто помогает её решить?\n\nА как вы поступаете в такой ситуации?',networks:[],date:new Date(Date.now()+86400000).toISOString(),status:'draft'});go('create')}},{label:'Расписание отправки',note:data.scheduler==='cron'?'Фоновый обработчик включён':'Отправка при открытом приложении',icon:Clock,run:()=>go('settings')}].map(item=><button key={item.label} onClick={item.run}><item.icon size={22}/><span><strong>{item.label}</strong><small>{item.note}</small></span><ChevronRight size={16}/></button>)}</section></aside></div></>}
 {view==='create'&&<><PageHeading title={editing?'Редактировать пост':'Создать пост'} subtitle="Создать → выбрать сети → запланировать"/><Composer key={editing?.id||initialDate||'new'} post={editing} initialDate={initialDate} data={data} upload={()=>uploadRef.current?.click()} onSave={save}/></>}
 {view==='content'&&<><PageHeading title="Ваш контент" subtitle="От первой мысли до опубликованной истории." action={()=>create()}/><div className="content-toolbar"><div className="tabs">{[['all','Все'],['scheduled','Запланировано'],['draft','Черновики'],['published','Опубликовано'],['error','Ошибки']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}<span>{id==='all'?posts.length:posts.filter(p=>p.status===id).length}</span></button>)}</div><div className="filters"><label className="search-box"><Search size={17}/><input aria-label="Поиск постов" placeholder="Найти пост…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Фильтр по соцсети" value={networkFilter} onChange={e=>setNetworkFilter(e.target.value)}><option value="all">Все соцсети</option>{networks.map(n=><option key={n}>{n}</option>)}</select></div></div><section className="panel content-list">{filtered.length?filtered.map(postRow):<Empty title="Здесь появятся ваши посты" text="Создайте первую публикацию или измените фильтры." action={()=>create()} label="Создать пост"/>}</section></>}
 {view==='calendar'&&<><PageHeading title="Контент-календарь" subtitle="Каждой идее — своё время." action={()=>create()}/><section className="panel calendar-panel"><div className="calendar-toolbar"><h2>{month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h2><div><button className="secondary" onClick={()=>setMonth(new Date())}>Сегодня</button><button className="icon-button" aria-label="Предыдущий месяц" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={19}/></button><button className="icon-button" aria-label="Следующий месяц" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={19}/></button></div></div><div className="calendar-scroll"><div className="calendar-grid">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(d=><div className="weekday" key={d}>{d}</div>)}{days.map(d=>{const value=localDay(d.toISOString());return <div key={value} className={`calendar-cell ${d.getMonth()!==month.getMonth()?'muted-cell':''}`}><button aria-label={`Создать пост на ${value}`} className={`date-number ${value===localDay(new Date().toISOString())?'current':''}`} onClick={()=>create(value+'T18:00')}>{d.getDate()}<Plus size={13}/></button>{posts.filter(p=>p.status!=='draft'&&localDay(p.date)===value).map(p=><button key={p.id} className={`calendar-event ${p.status}`} onClick={()=>setSelected(p)}><span>{new Date(p.date).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})} · {p.networks.join(' / ')}</span><strong>{p.title}</strong></button>)}</div>})}</div></div><div className="calendar-legend"><Badge status="scheduled"/><Badge status="published"/><span>{Intl.DateTimeFormat().resolvedOptions().timeZone}</span></div></section></>}
 {view==='media'&&<><PageHeading title="Медиатека" subtitle="Фотографии и видео для ваших будущих историй."/><div className="upload-area" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files)}}><Upload size={30}/><h2>Перетащите файлы сюда</h2><p>JPG, PNG, WebP, MP4 · до 20 МБ</p><button className="primary" disabled={busy} onClick={()=>uploadRef.current?.click()}>Выбрать файлы</button></div><div className="section-heading media-heading"><h2>Все файлы · {data.media.length}</h2><span className="muted">Приватное серверное хранилище</span></div><div className="media-grid">{data.media.map(m=><article className="media-card" key={m.id}><MediaView media={m}/><div><span>{m.name}</span><button disabled={busy} className="icon-button" aria-label={`Удалить ${m.name}`} onClick={()=>void action(()=>request(`/api/media/${m.id}`,'DELETE'),'Файл удалён')}><Trash2 size={16}/></button></div></article>)}</div></>}
 {view==='accounts'&&<><PageHeading title="Ваши социальные сети" subtitle="Подключите каналы и начните публиковать."/><div className="account-grid">{networks.map(n=><section className="panel account-card" key={n}><div className="section-heading"><Social network={n}/><span className={`badge ${data.accounts.includes(n)?'published':'draft'}`}>{data.accounts.includes(n)?'Подключено':'Не подключено'}</span></div><h2>{n}</h2><p>{n==='Telegram'?'Текст, фото JPG/PNG и видео MP4':n==='VK'?'Текстовые посты в сообщество':'Одиночное фото по публичной JPEG-ссылке'}</p><div className="account-handle">{data.accountDetails?.find(a=>a.network===n)?.label||'Добавьте аккаунт для публикации'}</div><button className="primary wide" onClick={()=>setConnect(n)}>{data.accounts.includes(n)?'Обновить подключение':'Подключить'}</button>{data.accounts.includes(n)&&<button className="text-button wide" disabled={busy} onClick={()=>void action(()=>request(`/api/accounts/${n}`,'DELETE'),'Аккаунт отключён')}>Отключить</button>}</section>)}</div><div className="info-banner"><Link2 size={20}/><span>Токены проверяются через API соцсети и хранятся зашифрованными. Пароли от соцсетей не нужны.</span></div></>}
 {view==='analytics'&&<><PageHeading title="Журнал публикаций" subtitle="Подтверждения отправки и ошибки по каждой социальной сети."/><section className="panel journal">{deliveries.length?deliveries.map(d=><DeliveryRow key={d.id} delivery={d} title={posts.find(p=>p.id===d.post_id)?.title||'Пост'} busy={busy} retry={()=>{if(d.status==='unknown'&&!window.confirm('Проверьте канал. Подтверждаете, что этой публикации там нет? Повтор может создать дубликат, если пост уже вышел.'))return;void action(()=>request(`/api/retry/${d.id}`,'POST',{confirmAbsent:d.status==='unknown'}),'Повторная отправка поставлена в очередь')}}/>):<Empty title="Первые результаты ещё впереди" text="Здесь будут реальные ответы подключённых соцсетей." action={()=>go('accounts')} label="Подключить соцсети"/>}</section></>}
 {view==='settings'&&<><PageHeading title="Ваше пространство" subtitle="Профиль, хранение и расписание."/><form className="panel settings-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(()=>request('/api/profile','POST',{name:f.get('name')}),'Имя сохранено')}}><h2>Личный профиль</h2><label>Ваше имя<input name="name" defaultValue={data.name} required maxLength={40}/></label><label>Email<input value={data.email} readOnly/></label><div className="setting-row"><div><strong>Часовой пояс</strong><p>{Intl.DateTimeFormat().resolvedOptions().timeZone}. На сервере время хранится в UTC.</p></div></div><div className="setting-row"><div><strong>Хранение</strong><p>Посты — в базе данных. Файлы — в приватной медиатеке.</p></div><span className="pill">Сервер</span></div><div className="setting-row"><div><strong>Автоматическая отправка</strong><p>{data.scheduler==='cron'?'Фоновый обработчик активен. Окно приложения можно закрыть.':'Очередь проверяется каждые 15 секунд, пока приложение открыто. После закрытия отправка возобновится при следующем входе. Для круглосуточной отправки требуется фоновый обработчик.'}</p></div></div><div className="setting-row"><div><strong>Ошибки и повторы</strong><p>Автоматических повторов нет. Проверьте результат в журнале и повторите только неудачную отправку.</p></div></div><button className="primary" disabled={busy}>Сохранить изменения</button></form></>}
 </main><footer>planly. <span>Personal SMM Planner</span><span>Ваш контент. Ваш ритм.</span></footer></div></div>
 {selected&&<Modal title="Просмотр поста" close={()=>setSelected(null)}><div className="section-heading"><Badge status={selected.status}/></div><h2>{selected.title}</h2><p className="muted">{fmt(selected.date)}</p>{selected.media&&<div className="detail-media"><MediaView media={selected.media}/></div>}<p className="post-text">{selected.text}</p><div className="network-chips">{selected.networks.map(n=><span key={n}><Social network={n} small/>{n}</span>)}</div><div className="modal-actions">{['draft','scheduled'].includes(selected.status)&&<button className="primary" onClick={()=>{setEditing(selected);setInitialDate('');setSelected(null);go('create')}}><PenLine size={16}/>Редактировать</button>}<button className="secondary" disabled={busy} onClick={()=>void action(async()=>{await request('/api/posts','POST',{...selected,id:crypto.randomUUID(),revision:undefined,title:selected.title+' (копия)',status:'draft'});setSelected(null)},'Копия сохранена')}><Copy size={16}/>Копия</button><button disabled={busy} className="icon-button danger" aria-label="Удалить пост из планировщика" onClick={()=>{if(!window.confirm('Удалить пост из планировщика? Уже опубликованный пост останется в соцсети.'))return;void action(async()=>{await request(`/api/posts/${selected.id}`,'DELETE');setSelected(null)},'Пост удалён')}}><Trash2 size={18}/></button></div></Modal>}
 {connect&&<Modal title={`Подключить ${connect}`} close={()=>setConnect(null)}><ConnectForm network={connect} done={async()=>{setConnect(null);await refresh();setToast('Аккаунт проверен и подключён')}}/></Modal>}
 {busy&&<div className="busy-indicator" role="status"><LoaderCircle size={17}/>Сохраняем…</div>}{toast&&<div role="status" className="toast"><CheckCircle2 size={19}/><span>{toast}</span><button aria-label="Закрыть уведомление" onClick={()=>setToast('')}><X size={16}/></button></div>}</>;
}
function PageHeading({title,subtitle,action}:{title:string;subtitle:string;action?:()=>void}){return <div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{action&&<button className="primary" onClick={action}><Plus size={18}/>Создать пост</button>}</div>}
function Empty({title,text,action,label}:{title:string;text:string;action:()=>void;label:string}){return <div className="empty"><FileText size={30}/><h3>{title}</h3><p>{text}</p><button className="secondary" onClick={action}>{label}</button></div>}
function Modal({children,title,close}:{children:React.ReactNode;title:string;close:()=>void}){const ref=useRef<HTMLElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement;ref.current?.querySelector<HTMLElement>('button,input')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,a[href]')||[]),first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);prev?.focus()}},[]);return <div className="modal-backdrop" onClick={close}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} className="post-modal" onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" aria-label="Закрыть" onClick={close}><X size={21}/></button>{children}</section></div>}
function ConnectForm({network,done}:{network:Network;done:()=>Promise<void>}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="connect-form" onSubmit={async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');try{await request('/api/accounts','POST',{network,token:f.get('token'),target:f.get('target')||''});form.reset();await done()}catch(e){setError(e instanceof Error?e.message:'Ошибка подключения')}finally{setBusy(false)}}}><Social network={network}/><h2>Подключить {network}</h2><p>{network==='Telegram'?'Создайте бота через @BotFather и добавьте его администратором вашего канала с правом публикации.':network==='VK'?'Нужен токен с правом wall и доступом к управлению сообществом. В MVP поддерживаются текстовые посты.':'Нужен профессиональный аккаунт и токен Instagram Login с правами instagram_business_basic и instagram_business_content_publish.'}</p>{network!=='Instagram'&&<label>{network==='Telegram'?'Канал: @имя или ID':'ID сообщества со знаком минус'}<input name="target" required placeholder={network==='Telegram'?'@my_channel':'-123456'}/></label>}<label>Токен доступа<input name="token" type="password" autoComplete="off" required maxLength={4096}/></label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Проверяем доступ…':'Проверить и подключить'}</button><p className="fine">Проверка подключения не публикует постов. Токен не возвращается в браузер после сохранения.</p></form>}
function DeliveryRow({delivery:d,title,busy,retry}:{delivery:Delivery;title:string;busy:boolean;retry:()=>void}){return <article className="delivery-row"><Social network={d.network}/><div><strong>{title}</strong><p>{fmt(d.due)} · {({pending:'В очереди',sending:'Отправляется',sent:'Доставлено',failed:'Ошибка',unknown:'Нужна проверка'})[d.status]}</p>{d.remote_id&&<small>ID публикации: {d.remote_id}</small>}{d.error&&<p className="delivery-error">{d.error}</p>}</div>{['failed','unknown'].includes(d.status)?<button className="secondary" disabled={busy} onClick={retry}>Повторить</button>:d.status==='sent'?<CheckCircle2 size={21}/>:<Clock size={21}/>}</article>}
